# Generated by Django 4.0.3 on 2022-04-04 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPropertyPermissionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('additional_phone', models.CharField(max_length=20)),
                ('bio_data', tinymce.models.HTMLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('skype', models.URLField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
