# Generated by Django 4.0.3 on 2022-04-04 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_postpropertypermissionmodel_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpropertypermissionmodel',
            name='user',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
