# Generated by Django 4.0 on 2022-01-24 13:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.TextField()),
                ('text', tinymce.models.HTMLField()),
                ('picture', models.ImageField(upload_to='blog_images/%Y/%m/%d/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
